# Generated by Django 5.2.7 on 2025-11-05 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face_recognition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.CharField(choices=[('facial', 'Facial Recognition'), ('manual', 'Manual Entry')], default='facial', max_length=20),
        ),
        migrations.AddField(
            model_name='class',
            name='enrollment_code',
            field=models.CharField(blank=True, max_length=12, unique=True),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('method', models.CharField(choices=[('facial', 'Facial Recognition'), ('manual', 'Manual Entry')], default='facial', max_length=20)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='attendance_photos/')),
                ('processed', models.BooleanField(default=False)),
                ('processing_status', models.CharField(default='pending', max_length=50)),
                ('class_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='face_recognition.class')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='attendance',
            name='attendance_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='records', to='face_recognition.attendancesession'),
        ),
    ]
